(define (problem BLOCKS-4-0)
(:domain BLOCKS)
(:objects D B A C - block)
(:INIT (CLEAR C) (CLEAR A) (CLEAR B) (CLEAR D) (ONTABLE C) (ONTABLE A)
 (ONTABLE B) (ONTABLE D) (HANDEMPTY))
(:goal ((pick-up ?x - block)@t1 (put-down ?x)@t2))
(:constraints (and
                         (before (t1 t5) t6)
                         (before (t2 t3) (t5))
                         (hold-before t1 ())
                         (hold-before t1 (t4 t5 t7))
                         (hold-after (t2) (and (not (ontable ?x))
                                          		   (not (clear ?x))
                                          		   (not (handempty))
                                          		   (holding ?x)))
                         (hold-between (t1) (t2) (and (clear ?x) (ontable ?x) (handempty)))
                         (hold-during (t1) (t2) (and (clear ?x)))
                         (at start (and (clear ?x) (ontable ?x) (handempty)))
                         (at end (and (not (ontable ?x))
                                            (not (clear ?x))
                                            (not (handempty))
                                            (holding ?x)))
                         (always (and (clear ?x) (ontable ?x) (handempty)))
                         (at-most-once (and (clear ?x) (ontable ?x) (handempty)))
                         (sometime (and (clear ?x) (ontable ?x) (handempty)))
                         (sometime-after (and (clear ?x) (ontable ?x) (handempty)) (and (ontable ?x) (handempty)))
                         (sometime-before (and (clear ?x) (ontable ?x) (handempty)) (and (clear ?x) (handempty)))
                         (always-within t4 (and (clear ?x) (ontable ?x) (handempty)) (and (clear ?x) (handempty)))
                         (within (t2 t3) (and (clear ?x) (ontable ?x) (handempty)))
                       )
)
)
