(define (problem blocks_0)
  (:domain blocks)
  (:objects D B A C - block)
  (:ini (clear C)
         (clear A)
         (clear B)
         (clear D)
         (ontable C)
         (ontable A)
         (ontable B)
         (ontable D)
         (handempty)
  )
  (:goal (and (on D C)
              (on C B)
              (on B A)
         )
  )
)
